# Titanic Dataset with Pandas

---

# By: Abubakar Asif
# Student ID: F2023266163

# Importing NumPy

In [ ]:
import numpy as np

# Importing Files from Google Drive to Google Colab

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/ML first project(gender classification)/Titanic-Dataset.csv'

import pandas as pd
df = pd.read_csv(file_path)

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# 1. Convert Age Column to NumPy Array

In [ ]:
age_array = df['Age'].values
age_array

array([22.  , 38.  , 26.  , 35.  , 35.  ,   nan, 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,   nan,
       31.  ,   nan, 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  ,   nan,
       19.  ,   nan,   nan, 40.  ,   nan,   nan, 66.  , 28.  , 42.  ,
         nan, 21.  , 18.  , 14.  , 40.  , 27.  ,   nan,  3.  , 19.  ,
         nan,   nan,   nan,   nan, 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  ,   nan, 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  ,   nan,   nan, 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  ,   nan,   nan,  0.83, 30.  , 22.  ,
       29.  ,   nan, 28.  , 17.  , 33.  , 16.  ,   nan, 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  ,   nan, 71.  , 23.  , 34.  ,
       34.  , 28.  ,   nan, 21.  , 33.  , 37.  , 28.  , 21.  ,   nan,
       38.  ,   nan, 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  ,   nan, 32.5 , 32.5 , 54.  , 12.  ,
         nan, 24.  ,

# 2. Get First 10 Names

In [ ]:
name_array = df['Name'].values[:10]
name_array


array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)'], dtype=object)

# 3. Mean Age of Passengers

In [ ]:
mean_age = np.mean(df['Age'].values)
mean_age

np.float64(nan)

# 4. Convert Fare Column to NumPy Array

In [ ]:
fare_array = df['Fare'].values
fare_array

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.0

# 5. Median Fare

In [ ]:
median_fare = np.median(df['Fare'].values)
median_fare

np.float64(14.4542)

# 6. Standard Deviation of Age

In [ ]:
mstd_age = np.std(df['Age'].values)
mstd_age

np.float64(nan)

# 7. Convert Pclass Column to NumPy Array

In [ ]:
pclass_array = df['Pclass'].values
pclass_array

array([3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2,
       3, 1, 3, 3, 3, 1, 3, 3, 1, 1, 3, 2, 1, 1, 3, 3, 3, 3, 3, 2, 3, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 1, 1, 2, 3, 2, 3, 3, 1, 1, 3, 1, 3,
       2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 2, 3, 3, 3,
       1, 3, 3, 3, 1, 3, 3, 3, 1, 1, 2, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3,
       1, 3, 3, 3, 3, 3, 3, 2, 1, 3, 2, 3, 2, 2, 1, 3, 3, 3, 3, 3, 3, 3,
       3, 2, 2, 2, 1, 1, 3, 1, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 2, 1, 3, 3,
       3, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 1, 3,
       3, 1, 2, 3, 3, 2, 3, 2, 3, 1, 3, 1, 3, 3, 2, 2, 3, 2, 1, 1, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 2, 3, 2, 3, 1, 3, 2, 1, 2,
       3, 2, 3, 3, 1, 3, 2, 3, 2, 3, 1, 3, 2, 3, 2, 3, 2, 2, 2, 2, 3, 3,
       2, 3, 3, 1, 3, 2, 1, 2, 3, 3, 1, 3, 3, 3, 1, 1, 1, 2, 3, 3, 1, 1,
       3, 2, 3, 3, 1, 1, 1, 3, 2, 1, 3, 1, 3, 2, 3, 3, 3, 3, 3, 3, 1, 3,
       3, 3, 2, 3, 1, 1, 2, 3, 3, 1, 3, 1, 1, 1, 3,

# 8. Count Missing Age Values

In [ ]:
missing_age_count = np.sum(np.isnan(df['Age'].values))
missing_age_count

np.int64(177)

# 9. Fill Missing Ages with Mean Age

In [ ]:

mean_age_for_filling = np.nanmean(df['Age'].values)

age_filled = np.where(np.isnan(df['Age'].values), mean_age_for_filling, df['Age'].values)
print("First 10 elements of age_filled array:", age_filled[:10])

std_age = np.std(age_filled)
print("Standard deviation of filled age array:", std_age)

First 10 elements of age_filled array: [22.         38.         26.         35.         35.         29.69911765
 54.          2.         27.         14.        ]
Standard deviation of filled age array: 12.99471687278903


# 10. Ages Above 50

In [ ]:
age_over_50 = df['Age'].values[df['Age'].values > 50]
age_over_50

array([54. , 58. , 55. , 66. , 65. , 59. , 71. , 70.5, 54. , 51. , 55.5,
       51. , 61. , 56. , 58. , 51. , 59. , 54. , 62. , 52. , 58. , 63. ,
       65. , 54. , 61. , 60. , 51. , 64. , 52. , 65. , 56. , 63. , 58. ,
       55. , 71. , 54. , 54. , 64. , 62. , 62. , 53. , 54. , 60. , 52. ,
       61. , 57. , 80. , 51. , 56. , 58. , 70. , 60. , 60. , 52. , 52. ,
       70. , 51. , 57. , 54. , 52. , 62. , 74. , 51. , 56. ])

# 11. Fares Above 100

In [ ]:
high_fares = df['Fare'].values[df['Fare'].values > 100]
high_fares

array([263.    , 146.5208, 263.    , 247.5208, 146.5208, 113.275 ,
       512.3292, 153.4625, 135.6333, 151.55  , 247.5208, 151.55  ,
       110.8833, 108.9   , 262.375 , 164.8667, 134.5   , 135.6333,
       153.4625, 133.65  , 134.5   , 263.    , 135.6333, 211.5   ,
       227.525 , 120.    , 113.275 , 120.    , 263.    , 151.55  ,
       108.9   , 221.7792, 106.425 , 106.425 , 110.8833, 227.525 ,
       110.8833, 153.4625, 113.275 , 133.65  , 512.3292, 211.3375,
       110.8833, 227.525 , 151.55  , 227.525 , 211.3375, 512.3292,
       262.375 , 120.    , 211.3375, 120.    , 164.8667])

# 12. Ages Between 20 and 40

In [ ]:
age_20_40 = df['Age'].values[(df['Age'].values >= 20) & (df['Age'].values <= 40)]
age_20_40

array([22. , 38. , 26. , 35. , 35. , 27. , 20. , 39. , 31. , 35. , 34. ,
       28. , 38. , 40. , 28. , 21. , 40. , 27. , 21. , 29. , 21. , 28.5,
       22. , 38. , 29. , 26. , 32. , 21. , 26. , 32. , 25. , 30. , 22. ,
       29. , 28. , 33. , 23. , 24. , 29. , 20. , 26. , 23. , 34. , 34. ,
       28. , 21. , 33. , 37. , 28. , 21. , 38. , 22. , 20. , 21. , 29. ,
       24. , 21. , 32.5, 32.5, 24. , 33. , 20. , 29. , 25. , 23. , 37. ,
       24. , 22. , 24. , 27. , 36.5, 22. , 30. , 40. , 26. , 28. , 21. ,
       30. , 36. , 40. , 36. , 32. , 24. , 28. , 34. , 32. , 26. , 40. ,
       24. , 35. , 22. , 30. , 31. , 27. , 32. , 30. , 27. , 38. , 22. ,
       20.5, 35. , 29. , 24. , 33. , 29. , 22. , 30. , 25. , 24. , 37. ,
       29. , 30. , 29. , 30. , 35. , 40. , 36. , 25. , 35. , 25. , 37. ,
       35. , 28. , 33. , 30. , 22. , 22. , 26. , 36. , 24. , 24. , 23.5,
       30. , 30. , 24. , 26. , 28. , 26. , 24. , 31. , 40. , 22. , 27. ,
       30. , 22. , 36. , 36. , 31. , 38. , 29. , 24

# 13. Number of Survivors

In [ ]:
survivors = np.sum(df['Survived'].values == 1)
survivors

np.int64(342)

# 14. Number of Non-Survivors

In [ ]:
non_survivors = np.sum(df['Survived'].values == 0)
non_survivors

np.int64(549)

# 15. Convert Sex Column to Numeric

In [ ]:
sex_numeric = np.where(df['Sex'].values == 'male', 1, 0)
sex_numeric

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,

# 16. Unique Passenger Classes

In [ ]:
unique_classes = np.unique(df['Pclass'].values)
unique_classes

array([1, 2, 3])

# 17. Count of Each Passenger Class

In [ ]:
class_counts = np.bincount(df['Pclass'].values)
class_counts

array([  0, 216, 184, 491])

# 18. Maximum Age

In [ ]:
max_age = np.nanmax(df['Age'].values)
max_age

np.float64(80.0)

# 19. Minimum Age

In [ ]:
min_age = np.nanmin(df['Age'].values)
min_age

np.float64(0.42)

# 20. Maximum Fare

In [ ]:
max_fare = np.max(df['Fare'].values)
max_fare

np.float64(512.3292)

# 21. Minimum Fare

In [ ]:
min_fare = np.min(df['Fare'].values)
min_fare

np.float64(0.0)

# 22. Sum of All Fares

In [ ]:
total_fare = np.sum(df['Fare'].values)
total_fare

np.float64(28693.9493)

# 23. Cumulative Sum of Fares

In [ ]:
cumsum_fare = np.cumsum(df['Fare'].values)
cumsum_fare


array([7.25000000e+00, 7.85333000e+01, 8.64583000e+01, 1.39558300e+02,
       1.47608300e+02, 1.56066600e+02, 2.07929100e+02, 2.29004100e+02,
       2.40137400e+02, 2.70208200e+02, 2.86908200e+02, 3.13458200e+02,
       3.21508200e+02, 3.52783200e+02, 3.60637400e+02, 3.76637400e+02,
       4.05762400e+02, 4.18762400e+02, 4.36762400e+02, 4.43987400e+02,
       4.69987400e+02, 4.82987400e+02, 4.91016600e+02, 5.26516600e+02,
       5.47591600e+02, 5.78979100e+02, 5.86204100e+02, 8.49204100e+02,
       8.57083300e+02, 8.64979100e+02, 8.92699900e+02, 1.03922070e+03,
       1.04697070e+03, 1.05747070e+03, 1.13964150e+03, 1.19164150e+03,
       1.19887070e+03, 1.20692070e+03, 1.22492070e+03, 1.23616240e+03,
       1.24563740e+03, 1.26663740e+03, 1.27453320e+03, 1.31611240e+03,
       1.32399160e+03, 1.33204160e+03, 1.34754160e+03, 1.35529160e+03,
       1.37697080e+03, 1.39477080e+03, 1.43445830e+03, 1.44225830e+03,
       1.51898750e+03, 1.54498750e+03, 1.60696670e+03, 1.64246670e+03,
      

# 24. Cumulative Product of Fares

In [ ]:
cumprod_fare = np.cumprod(df['Fare'].values)
cumprod_fare


array([7.25000000e+000, 5.16803925e+002, 4.09567111e+003, 2.17480136e+005,
       1.75071509e+006, 1.48080735e+007, 7.67983710e+008, 1.61852567e+010,
       1.80195318e+011, 5.41861738e+012, 9.04909102e+013, 2.40253367e+015,
       1.93403960e+016, 6.04870885e+017, 4.75077691e+018, 7.60124305e+019,
       2.21386204e+021, 2.87802065e+022, 5.18043717e+023, 3.74286586e+024,
       9.73145123e+025, 1.26508866e+027, 1.01576499e+028, 3.60596570e+029,
       7.59957272e+030, 2.38531589e+032, 1.72339073e+033, 4.53251761e+035,
       3.57126128e+036, 2.81979648e+037, 7.81670143e+038, 1.14530935e+041,
       8.87614744e+041, 9.31995481e+042, 7.65828142e+044, 3.98230634e+046,
       2.87888890e+047, 2.31750556e+048, 4.17151002e+049, 4.68948641e+050,
       4.44328838e+051, 9.33090559e+052, 7.36749644e+053, 3.06334608e+055,
       2.41367164e+056, 1.94300567e+057, 3.01165879e+058, 2.33403556e+059,
       5.06000238e+060, 9.00680424e+061, 3.57457543e+063, 2.78816884e+064,
       2.13933964e+066, 5

# 25. Ages Rounded to Nearest Integer

In [ ]:
rounded_age = np.rint(df['Age'].values)
rounded_age


array([22., 38., 26., 35., 35., nan, 54.,  2., 27., 14.,  4., 58., 20.,
       39., 14., 55.,  2., nan, 31., nan, 35., 34., 15., 28.,  8., 38.,
       nan, 19., nan, nan, 40., nan, nan, 66., 28., 42., nan, 21., 18.,
       14., 40., 27., nan,  3., 19., nan, nan, nan, nan, 18.,  7., 21.,
       49., 29., 65., nan, 21., 28.,  5., 11., 22., 38., 45.,  4., nan,
       nan, 29., 19., 17., 26., 32., 16., 21., 26., 32., 25., nan, nan,
        1., 30., 22., 29., nan, 28., 17., 33., 16., nan, 23., 24., 29.,
       20., 46., 26., 59., nan, 71., 23., 34., 34., 28., nan, 21., 33.,
       37., 28., 21., nan, 38., nan, 47., 14., 22., 20., 17., 21., 70.,
       29., 24.,  2., 21., nan, 32., 32., 54., 12., nan, 24., nan, 45.,
       33., 20., 47., 29., 25., 23., 19., 37., 16., 24., nan, 22., 24.,
       19., 18., 19., 27.,  9., 36., 42., 51., 22., 56., 40., nan, 51.,
       16., 30., nan, nan, 44., 40., 26., 17.,  1.,  9., nan, 45., nan,
       28., 61.,  4.,  1., 21., 56., 18., nan, 50., 30., 36., na

# 26. Log of Fares

In [ ]:
log_fares = np.log(df['Fare'].values + 1)
log_fares


array([2.1102132 , 4.28059312, 2.18885633, 3.99083419, 2.20276476,
       2.24689266, 3.9676942 , 3.09444575, 2.49595374, 3.43626847,
       2.87356464, 3.31600254, 2.20276476, 3.47429294, 2.18089192,
       2.83321334, 3.40535539, 2.63905733, 2.94443898, 2.1071783 ,
       3.29583687, 2.63905733, 2.20046377, 3.59731226, 3.09444575,
       3.47777255, 2.1071783 , 5.5759491 , 2.18371146, 2.18557926,
       3.3576216 , 4.99396918, 2.1690537 , 2.44234704, 4.42089632,
       3.97029191, 2.1076888 , 2.20276476, 2.94443898, 2.50484816,
       2.34899147, 3.09104245, 2.18557926, 3.75136587, 2.18371146,
       2.20276476, 2.80336038, 2.1690537 , 3.1214482 , 2.93385687,
       3.70592092, 2.17475172, 4.35323099, 3.29583687, 4.14280451,
       3.59731226, 2.44234704, 2.1076888 , 3.35863777, 3.8691155 ,
       2.1076888 , 4.39444915, 4.43645563, 3.3638416 , 3.3576216 ,
       2.78783441, 2.44234704, 2.21466057, 2.18885633, 2.26825241,
       2.44234704, 3.8691155 , 4.31079913, 2.73788081, 4.05171

# 27. Ages Squared

In [ ]:
age_squared = np.square(df['Age'].values)
age_squared

array([4.84000e+02, 1.44400e+03, 6.76000e+02, 1.22500e+03, 1.22500e+03,
               nan, 2.91600e+03, 4.00000e+00, 7.29000e+02, 1.96000e+02,
       1.60000e+01, 3.36400e+03, 4.00000e+02, 1.52100e+03, 1.96000e+02,
       3.02500e+03, 4.00000e+00,         nan, 9.61000e+02,         nan,
       1.22500e+03, 1.15600e+03, 2.25000e+02, 7.84000e+02, 6.40000e+01,
       1.44400e+03,         nan, 3.61000e+02,         nan,         nan,
       1.60000e+03,         nan,         nan, 4.35600e+03, 7.84000e+02,
       1.76400e+03,         nan, 4.41000e+02, 3.24000e+02, 1.96000e+02,
       1.60000e+03, 7.29000e+02,         nan, 9.00000e+00, 3.61000e+02,
               nan,         nan,         nan,         nan, 3.24000e+02,
       4.90000e+01, 4.41000e+02, 2.40100e+03, 8.41000e+02, 4.22500e+03,
               nan, 4.41000e+02, 8.12250e+02, 2.50000e+01, 1.21000e+02,
       4.84000e+02, 1.44400e+03, 2.02500e+03, 1.60000e+01,         nan,
               nan, 8.41000e+02, 3.61000e+02, 2.89000e+02, 6.760

# 28. Ages Standardized

In [ ]:
standardized_age = (df['Age'].values - np.nanmean(df['Age'].values)) / np.nanstd(df['Age'].values)
standardized_age


array([-0.53037664,  0.57183099, -0.25482473,  0.36516706,  0.36516706,
               nan,  1.67403863, -1.90813618, -0.18593675, -1.08148046,
       -1.77036023,  1.94959054, -0.6681526 ,  0.64071897, -1.08148046,
        1.74292661, -1.90813618,         nan,  0.08961515,         nan,
        0.36516706,  0.29627909, -1.01259248, -0.11704878, -1.49480832,
        0.57183099,         nan, -0.73704057,         nan,         nan,
        0.70960695,         nan,         nan,  2.50069435, -0.11704878,
        0.8473829 ,         nan, -0.59926462, -0.80592855, -1.08148046,
        0.70960695, -0.18593675,         nan, -1.83924821, -0.73704057,
               nan,         nan,         nan,         nan, -0.80592855,
       -1.5636963 , -0.59926462,  1.32959874, -0.0481608 ,  2.43180638,
               nan, -0.59926462, -0.08260479, -1.70147225, -1.28814439,
       -0.53037664,  0.57183099,  1.05404683, -1.77036023,         nan,
               nan, -0.0481608 , -0.73704057, -0.87481653, -0.25

# 29. Fare Z-Scores

In [ ]:
fare_z = (df['Fare'].values - np.mean(df['Fare'].values)) / np.std(df['Fare'].values)
fare_z

array([-5.02445171e-01,  7.86845294e-01, -4.88854258e-01,  4.20730236e-01,
       -4.86337422e-01, -4.78116429e-01,  3.95813561e-01, -2.24083121e-01,
       -4.24256141e-01, -4.29555021e-02, -3.12172378e-01, -1.13845709e-01,
       -4.86337422e-01, -1.87093118e-02, -4.90279793e-01, -3.26266659e-01,
       -6.19988892e-02, -3.86670720e-01, -2.85997284e-01, -5.02948539e-01,
       -1.24919787e-01, -3.86670720e-01, -4.86756223e-01,  6.63597416e-02,
       -2.24083121e-01, -1.64441595e-02, -5.02948539e-01,  4.64700108e+00,
       -4.89776426e-01, -4.89442190e-01, -9.02720170e-02,  2.30172882e+00,
       -4.92377828e-01, -4.37007438e-01,  1.00606170e+00,  3.98582080e-01,
       -5.02863973e-01, -4.86337422e-01, -2.85997284e-01, -4.22073541e-01,
       -4.57645492e-01, -2.25593223e-01, -4.89442190e-01,  1.88762532e-01,
       -4.89776426e-01, -4.86337422e-01, -3.36334002e-01, -4.92377828e-01,
       -2.11917743e-01, -2.90024222e-01,  1.50673744e-01, -4.91371093e-01,
        8.96496787e-01, -

# 30. Sort Ages

In [ ]:
sorted_ages = np.sort(df['Age'].values)
sorted_ages

array([ 0.42,  0.67,  0.75,  0.75,  0.83,  0.83,  0.92,  1.  ,  1.  ,
        1.  ,  1.  ,  1.  ,  1.  ,  1.  ,  2.  ,  2.  ,  2.  ,  2.  ,
        2.  ,  2.  ,  2.  ,  2.  ,  2.  ,  2.  ,  3.  ,  3.  ,  3.  ,
        3.  ,  3.  ,  3.  ,  4.  ,  4.  ,  4.  ,  4.  ,  4.  ,  4.  ,
        4.  ,  4.  ,  4.  ,  4.  ,  5.  ,  5.  ,  5.  ,  5.  ,  6.  ,
        6.  ,  6.  ,  7.  ,  7.  ,  7.  ,  8.  ,  8.  ,  8.  ,  8.  ,
        9.  ,  9.  ,  9.  ,  9.  ,  9.  ,  9.  ,  9.  ,  9.  , 10.  ,
       10.  , 11.  , 11.  , 11.  , 11.  , 12.  , 13.  , 13.  , 14.  ,
       14.  , 14.  , 14.  , 14.  , 14.  , 14.5 , 15.  , 15.  , 15.  ,
       15.  , 15.  , 16.  , 16.  , 16.  , 16.  , 16.  , 16.  , 16.  ,
       16.  , 16.  , 16.  , 16.  , 16.  , 16.  , 16.  , 16.  , 16.  ,
       16.  , 17.  , 17.  , 17.  , 17.  , 17.  , 17.  , 17.  , 17.  ,
       17.  , 17.  , 17.  , 17.  , 17.  , 18.  , 18.  , 18.  , 18.  ,
       18.  , 18.  , 18.  , 18.  , 18.  , 18.  , 18.  , 18.  , 18.  ,
       18.  , 18.  ,

# 31. Indices that Would Sort Age

In [ ]:
age_sort_indices = np.argsort(df['Age'].values)
age_sort_indices

array([803, 755, 469, 644, 831,  78, 305, 788, 381, 827, 386, 164, 172,
       183, 205, 119, 297, 530, 642, 824,   7, 340,  16, 479, 374,  43,
       348, 193, 261, 407, 850, 618,  10, 184, 171,  63, 750, 869, 691,
       445,  58, 448, 777, 233, 751, 813, 720, 535, 278,  50, 549, 787,
       237,  24, 489, 147, 541, 634, 852, 165, 480, 182, 819, 419,  59,
       802, 731, 542, 125, 446, 780, 435,  39,  14,   9, 683, 686, 111,
       875,  22, 352, 830, 689,  71, 791, 746, 266, 504, 853, 208, 156,
       574, 764, 329,  86, 333, 841, 282, 220, 138, 532, 307, 844, 163,
       781, 114, 389, 433, 550, 721,  84, 500,  68, 702, 385, 144, 424,
       417, 757, 228,  38, 700, 688, 204, 505, 855, 677, 675, 371, 175,
       651, 654, 775, 585, 311, 786,  49, 807, 834, 748, 877, 191, 192,
       379,  27, 575, 302,  67, 646, 238, 715, 566, 546, 687, 136, 283,
       427, 372, 143, 291, 145, 226,  44, 887, 113, 876, 725, 378, 664,
        12, 682, 640, 404,  91, 762, 441, 840, 131, 622, 227, 49

# 32. Unique Embarked Values

In [ ]:
unique_embarked = np.unique(df['Embarked'].astype(str))
unique_embarked

array(['C', 'Q', 'S', 'nan'], dtype=object)

# 33. Count of Each Embarked Value

In [ ]:
embarked_array = df['Embarked'].values
embarked_counts = [np.sum(embarked_array == val) for val in unique_embarked]
embarked_counts

[np.int64(168), np.int64(77), np.int64(644), np.int64(0)]

# 34. Convert Parch Column to NumPy Array

In [ ]:
parch_array = df['Parch'].values
parch_array

array([0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 5, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1,
       0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0,
       2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 2,
       0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 1, 2, 1, 4, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 2, 0, 2, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0,

# 35. Convert SibSp Column to NumPy Array

In [ ]:
sibsp_array = df['SibSp'].values
sibsp_array

array([1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 1, 0, 0, 1, 0, 0, 4, 0, 1, 0, 0, 0,
       0, 0, 3, 1, 0, 3, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 2, 1, 4, 0, 1, 1, 0, 0, 0, 0, 1, 5, 0, 0, 1, 3, 0, 1,
       0, 0, 4, 2, 0, 5, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0,
       3, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 4, 2, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 4, 0, 0, 1, 0, 0, 0, 4, 1, 0, 0, 1,
       3, 0, 0, 0, 8, 0, 4, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 8, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 1, 0, 0, 4, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 4, 1, 0,
       0, 0, 4, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 4, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,

# 36. Total Family Members

In [ ]:
total_family = df['SibSp'].values + df['Parch'].values
total_family

array([ 1,  1,  0,  1,  0,  0,  0,  4,  2,  1,  2,  0,  0,  6,  0,  0,  5,
        0,  1,  0,  0,  0,  0,  0,  4,  6,  0,  5,  0,  0,  0,  1,  0,  0,
        1,  1,  0,  0,  2,  1,  1,  1,  0,  3,  0,  0,  1,  0,  2,  1,  5,
        0,  1,  1,  1,  0,  0,  0,  3,  7,  0,  0,  1,  5,  0,  2,  0,  0,
        6,  2,  0,  7,  0,  1,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,
        3,  4,  0,  5,  0,  0,  0,  1,  3,  0,  0,  0,  1,  1,  1,  0,  0,
        1,  0,  2,  0,  0,  0,  0,  1,  0,  1,  0,  1,  0,  0,  0,  1,  1,
        6,  2,  0,  1,  0,  1,  1,  0,  0,  2,  0,  0,  0,  1,  1,  0,  0,
        2,  1,  0,  0,  2,  0,  1,  0,  0,  2,  0,  4,  2,  0,  0,  1,  0,
        2,  0,  1,  0,  0,  0, 10,  1,  0,  0,  0,  5,  2,  1,  5,  0,  0,
        0,  5,  2,  0,  0,  2,  4,  0,  0,  0, 10,  0,  6,  3,  2,  0,  1,
        0,  2,  0,  0,  0,  1,  2,  0,  0,  0,  1,  0,  0,  0, 10,  0,  0,
        0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  1,  0,  0,  0,
        0,  0,  0,  1,  0

# 37. Filter Passengers with Family Size > 3

In [ ]:
total_family = df['SibSp'].values + df['Parch'].values
large_family = total_family[total_family > 3]
large_family

array([ 4,  6,  5,  4,  6,  5,  5,  7,  5,  6,  7,  4,  5,  6,  4, 10,  5,
        5,  5,  4, 10,  6, 10,  4,  6,  6,  5,  5,  4, 10,  5,  5,  4,  7,
        4,  4,  5,  5,  7,  4,  6,  6,  4,  6,  5,  5,  5,  7,  7,  5,  4,
        4,  4,  5, 10,  6,  5,  5, 10,  6, 10,  5])

# 38. Ages Not Missing

In [ ]:
non_missing_ages = df['Age'].values[~np.isnan(df['Age'].values)]
non_missing_ages

array([22.  , 38.  , 26.  , 35.  , 35.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 31.  , 35.  ,
       34.  , 15.  , 28.  ,  8.  , 38.  , 19.  , 40.  , 66.  , 28.  ,
       42.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 18.  ,
        7.  , 21.  , 49.  , 29.  , 65.  , 21.  , 28.5 ,  5.  , 11.  ,
       22.  , 38.  , 45.  ,  4.  , 29.  , 19.  , 17.  , 26.  , 32.  ,
       16.  , 21.  , 26.  , 32.  , 25.  ,  0.83, 30.  , 22.  , 29.  ,
       28.  , 17.  , 33.  , 16.  , 23.  , 24.  , 29.  , 20.  , 46.  ,
       26.  , 59.  , 71.  , 23.  , 34.  , 34.  , 28.  , 21.  , 33.  ,
       37.  , 28.  , 21.  , 38.  , 47.  , 14.5 , 22.  , 20.  , 17.  ,
       21.  , 70.5 , 29.  , 24.  ,  2.  , 21.  , 32.5 , 32.5 , 54.  ,
       12.  , 24.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  , 23.  ,
       19.  , 37.  , 16.  , 24.  , 22.  , 24.  , 19.  , 18.  , 19.  ,
       27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 , 40.5 , 51.  ,
       16.  , 30.  ,

# 39. Shuffle Passenger IDs

In [ ]:
passenger_ids = df['PassengerId'].values.copy()
np.random.shuffle(passenger_ids)
passenger_ids

array([208, 194,  64, 547, 549, 849, 266, 500, 869, 876, 130,  32, 487,
       433, 620, 815, 776,  55, 843, 310, 516, 811, 324, 136,  36, 455,
        99, 411, 773, 302, 741, 280,  69, 554, 648, 308,  10, 511, 513,
       626, 627,  19, 605, 398, 880, 288, 791, 689, 267, 401, 283, 460,
       470, 533, 316, 231, 384, 574, 508, 330, 538, 482, 364, 659, 164,
       350, 274, 647, 149, 400, 510, 501, 768, 769, 360, 106, 477, 357,
       891, 565, 752, 425, 600, 683, 491, 534, 714, 169, 212, 368,  91,
       669, 755,  66, 107, 840, 196, 456, 680, 305, 207, 119, 588, 334,
       602, 446, 145,  77, 404, 512, 151, 706, 252, 481, 405, 228, 506,
       205,  18,  79, 296, 803,  89, 225, 156, 219, 619, 321, 785, 442,
       147, 236, 188, 298, 238, 862, 340, 248, 410,  63,  39,  33, 860,
       387, 836, 598, 109, 417, 796, 593, 758, 582, 546, 132,  48, 559,
       808, 314, 492, 480, 524, 157,  47, 158, 656, 391, 495, 848,   7,
       633,  35, 388, 180, 318,  68, 359, 691, 486, 200, 886,  2

# 40. Random Sample of 10 Ages

In [ ]:
random_ages = np.random.choice(df['Age'].values[~np.isnan(df['Age'].values)], size=10, replace=False)
random_ages

array([30., 19., 22.,  1., 50., 48., 20., 20., 21., 44.])

# 41. Compare Age > Mean Age

In [ ]:
age_gt_mean = df['Age'].values > np.nanmean(df['Age'].values)
age_gt_mean

array([False,  True, False,  True,  True, False,  True, False, False,
       False, False,  True, False,  True, False,  True, False, False,
        True, False,  True,  True, False, False, False,  True, False,
       False, False, False,  True, False, False,  True, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
        True, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True, False,  True, False,  True,
        True, False, False, False,  True,  True, False, False, False,
        True, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True,  True,  True, False,
       False, False,

# 42. Fare Above Mean Fare

In [ ]:
fare_gt_mean = df['Fare'].values > np.mean(df['Fare'].values)
fare_gt_mean

array([False,  True, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False,  True, False,
        True,  True, False, False, False,  True, False,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False,  True, False,
       False, False,  True, False, False, False,  True,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False,  True, False,
       False, False,

# 43. Ages Not Between 20 and 40

In [ ]:
age_not_20_40 = ~((df['Age'].values >= 20) & (df['Age'].values <= 40))
age_not_20_40

array([False, False, False, False, False,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
       False, False, False, False,  True,  True,  True, False, False,
       False,  True, False,  True, False,  True,  True, False, False,
       False, False,  True, False,  True,  True,  True, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False,  True,  True,  True, False, False,  True, False,  True,
       False, False,  True, False,  True, False, False,  True,  True,
        True, False,

# 44. Passengers Who Survived and Are Female

In [ ]:
female_survivors = (df['Sex'].values == 'female') & (df['Survived'].values == 1)
female_survivors

array([False,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True, False, False,
       False,  True, False, False,  True, False, False,  True, False,
       False,  True, False, False,  True,  True, False, False, False,
       False, False, False,  True, False, False, False,  True,  True,
       False, False,  True, False, False, False, False,  True,  True,
       False, False,  True, False,  True, False, False,  True, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False,  True,  True, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False,

# 45. Passengers Who Survived and Are Male

In [ ]:
male_survivors = (df['Sex'].values == 'male') & (df['Survived'].values == 1)
male_survivors

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True,

# 46. Ages Rounded Down

In [ ]:
ages_floor = np.floor(df['Age'].values)
ages_floor

array([22., 38., 26., 35., 35., nan, 54.,  2., 27., 14.,  4., 58., 20.,
       39., 14., 55.,  2., nan, 31., nan, 35., 34., 15., 28.,  8., 38.,
       nan, 19., nan, nan, 40., nan, nan, 66., 28., 42., nan, 21., 18.,
       14., 40., 27., nan,  3., 19., nan, nan, nan, nan, 18.,  7., 21.,
       49., 29., 65., nan, 21., 28.,  5., 11., 22., 38., 45.,  4., nan,
       nan, 29., 19., 17., 26., 32., 16., 21., 26., 32., 25., nan, nan,
        0., 30., 22., 29., nan, 28., 17., 33., 16., nan, 23., 24., 29.,
       20., 46., 26., 59., nan, 71., 23., 34., 34., 28., nan, 21., 33.,
       37., 28., 21., nan, 38., nan, 47., 14., 22., 20., 17., 21., 70.,
       29., 24.,  2., 21., nan, 32., 32., 54., 12., nan, 24., nan, 45.,
       33., 20., 47., 29., 25., 23., 19., 37., 16., 24., nan, 22., 24.,
       19., 18., 19., 27.,  9., 36., 42., 51., 22., 55., 40., nan, 51.,
       16., 30., nan, nan, 44., 40., 26., 17.,  1.,  9., nan, 45., nan,
       28., 61.,  4.,  1., 21., 56., 18., nan, 50., 30., 36., na

# 47. Ages Rounded Up

In [ ]:
ages_ceil = np.ceil(df['Age'].values)
ages_ceil

array([22., 38., 26., 35., 35., nan, 54.,  2., 27., 14.,  4., 58., 20.,
       39., 14., 55.,  2., nan, 31., nan, 35., 34., 15., 28.,  8., 38.,
       nan, 19., nan, nan, 40., nan, nan, 66., 28., 42., nan, 21., 18.,
       14., 40., 27., nan,  3., 19., nan, nan, nan, nan, 18.,  7., 21.,
       49., 29., 65., nan, 21., 29.,  5., 11., 22., 38., 45.,  4., nan,
       nan, 29., 19., 17., 26., 32., 16., 21., 26., 32., 25., nan, nan,
        1., 30., 22., 29., nan, 28., 17., 33., 16., nan, 23., 24., 29.,
       20., 46., 26., 59., nan, 71., 23., 34., 34., 28., nan, 21., 33.,
       37., 28., 21., nan, 38., nan, 47., 15., 22., 20., 17., 21., 71.,
       29., 24.,  2., 21., nan, 33., 33., 54., 12., nan, 24., nan, 45.,
       33., 20., 47., 29., 25., 23., 19., 37., 16., 24., nan, 22., 24.,
       19., 18., 19., 27.,  9., 37., 42., 51., 22., 56., 41., nan, 51.,
       16., 30., nan, nan, 44., 40., 26., 17.,  1.,  9., nan, 45., nan,
       28., 61.,  4.,  1., 21., 56., 18., nan, 50., 30., 36., na

# 48. Check if Fare > 50 and Pclass = 1

In [ ]:
high_fare_first_class = (df['Fare'].values > 50) & (df['Pclass'].values == 1)
high_fare_first_class

array([False,  True, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
        True, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False,

# 49. Extract Top 5 Highest Fares

In [ ]:
top5_fares = np.partition(df['Fare'].values, -5)[-5:]
top5_fares

array([263.    , 263.    , 512.3292, 512.3292, 512.3292])

# 50. Ages Normalized Between 0 and 1

In [ ]:
ages_norm = (df['Age'].values - np.nanmin(df['Age'].values)) / (np.nanmax(df['Age'].values) - np.nanmin(df['Age'].values))
ages_norm

array([0.27117366, 0.4722292 , 0.32143755, 0.43453129, 0.43453129,
              nan, 0.67328474, 0.01985423, 0.33400352, 0.17064589,
       0.04498618, 0.72354863, 0.24604172, 0.48479517, 0.17064589,
       0.68585072, 0.01985423,        nan, 0.3842674 ,        nan,
       0.43453129, 0.42196532, 0.18321186, 0.34656949, 0.09525006,
       0.4722292 ,        nan, 0.23347575,        nan,        nan,
       0.49736115,        nan,        nan, 0.8240764 , 0.34656949,
       0.52249309,        nan, 0.25860769, 0.22090978, 0.17064589,
       0.49736115, 0.33400352,        nan, 0.03242021, 0.23347575,
              nan,        nan,        nan,        nan, 0.22090978,
       0.08268409, 0.25860769, 0.61045489, 0.35913546, 0.81151043,
              nan, 0.25860769, 0.35285248, 0.05755215, 0.13294798,
       0.27117366, 0.4722292 , 0.560191  , 0.04498618,        nan,
              nan, 0.35913546, 0.23347575, 0.2083438 , 0.32143755,
       0.39683338, 0.19577783, 0.25860769, 0.32143755, 0.39683